
name: Tod
on:
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Update
         run: |
             sudo useradd -m las && sudo adduser las sudo && echo 'las:las' | sudo chpasswd
             whoami
